version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dsw
      - POSTGRES_USER=dsw
      - POSTGRES_PASSWORD=dsw123
  web:
    build: .
    command:
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
