# Generated by Django 4.1.3 on 2022-12-11 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja_Django', '0002_actor_name_actor_surname_director_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplikacja_Django.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='actor',
            name='surname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='director',
            name='surname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=360),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
