# Generated by Django 4.1.3 on 2022-12-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja_Django', '0004_alter_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
